[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
port = 8503                # change to a free port
enableCORS = true          # must be true to avoid XSRF conflict
enableXsrfProtection = true
